# https://github.com/JohnnyMorganz/StyLua?tab=readme-ov-file#options

column_width = 150
indent_type = 'Spaces'
indent_width = 2
quote_style = 'AutoPreferSingle'
call_parentheses = 'None'
collapse_simple_statement = 'Always'

[sort_requires]
enabled = true
